apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: policy-controller-operator
  namespace: openshift-policy-controller-operator
spec:
  channel: stable-v1.0
  name: policy-controller-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
