---
# Source: omniverse-nucleus/templates/services/discovery.yaml
apiVersion: v1
kind: Service
metadata:
  name: nucleus-discovery
  namespace: omniverse-nucleus
  labels:
    app: nucleus-discovery
    app.kubernetes.io/part-of: omniverse-nucleus
    app.kubernetes.io/version: "2023.2.9"
spec:
  selector:
    app: nucleus-discovery
  ports:
    - name: discovery
      port: 3333
      targetPort: 3333
---
# Source: omniverse-nucleus/templates/services/discovery.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-discovery
  namespace: omniverse-nucleus
  labels:
    app: nucleus-discovery
    app.kubernetes.io/part-of: omniverse-nucleus
    app.kubernetes.io/version: "2023.2.9"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: nucleus-discovery
  template:
    metadata:
      labels:
        app: nucleus-discovery
    spec:
      serviceAccountName: nucleus
      imagePullSecrets:
        - name: ngc-pull-secret
      containers:
        - name: nucleus-discovery
          image: nvcr.io/nvidia/omniverse/nucleus-discovery:1.5.5
          env:
            - name: ACCEPT_EULA
              value: "1"
            - name: CANONICAL_NAME
              value: "nucleus.apps.jary-qs-0323.7w5j.p1.openshiftapps.com"
            - name: SERVICE_TOKEN
              value: /omni/secrets/SERVICE_TOKEN
            - name: SERVICE_PUBLIC_KEY
              value: /omni/secrets/SERVICE_PUBLIC_KEY
            - name: WS_MAX_HTTP_LINE
              value: "65535"
            - name: SERVICE_STRUCTURED_LOGGING
              value: "0"
            - name: SERVICE_DEPLOYMENTS
              value: |
                reg:
                  - name: external
                    transport:
                      type: sows
                      params:
                        host: nucleus.apps.jary-qs-0323.7w5j.p1.openshiftapps.com
                        port: 80
                        path: /omni/discovery
                  - name: internal
                    transport:
                      type: sows
                      params:
                        host: nucleus-discovery
                        port: 3333
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 3333
          readinessProbe:
            tcpSocket:
              port: 3333
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3333
            initialDelaySeconds: 180
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_TOKEN
              subPath: svc_reg_token
              readOnly: true
            - name: crypto-secrets
              mountPath: /omni/secrets/SERVICE_PUBLIC_KEY
              subPath: auth_root_of_trust_pub
              readOnly: true
      volumes:
        - name: crypto-secrets
          secret:
            secretName: crypto-secrets
