---
# Source: omniverse-nucleus/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nucleus
  labels:
    app.kubernetes.io/part-of: omniverse-nucleus
    app.kubernetes.io/version: "2023.2.9"
