---
# Source: omniverse-nucleus/templates/services/lft-lb.yaml
apiVersion: v1
kind: Service
metadata:
  name: nucleus-lft-lb
  labels:
    app: nucleus-lft-lb
    app.kubernetes.io/part-of: omniverse-nucleus
    app.kubernetes.io/version: "2023.2.9"
spec:
  selector:
    app: nucleus-lft-lb
  ports:
    - name: lft
      port: 3030
      targetPort: 3030
---
# Source: omniverse-nucleus/templates/services/lft-lb.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus-lft-lb
  labels:
    app: nucleus-lft-lb
    app.kubernetes.io/part-of: omniverse-nucleus
    app.kubernetes.io/version: "2023.2.9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nucleus-lft-lb
  template:
    metadata:
      labels:
        app: nucleus-lft-lb
    spec:
      serviceAccountName: nucleus
      imagePullSecrets:
        - name: ngc-pull-secret
      containers:
        - name: nucleus-lft-lb
          image: nvcr.io/nvidia/omniverse/nucleus-lft-lb:1.14.53
          env:
            - name: ACCEPT_EULA
              value: "1"
            - name: NGINX_WORKER_PROCESSES
              value: auto
            - name: NGINX_WORKER_CONNECTIONS
              value: "10240"
            - name: NGINX_MAX_BODY_SIZE
              value: 10m
            - name: OMNI_LFT_RR_HOSTNAME
              value: nucleus-lft
            - name: OMNI_LFT_PORT
              value: "3030"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 3030
