apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: vla-training
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  apiServer:
    deploy: true
    enableSamplePipeline: false
  persistenceAgent:
    deploy: true
  scheduledWorkflow:
    deploy: true
  database:
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      resources:
        requests:
          cpu: 300m
          memory: 800Mi
        limits:
          cpu: "1"
          memory: 1Gi
  objectStorage:
    externalStorage:
      host: minio.mlflow.svc.cluster.local
      port: "9000"
      bucket: vla-training
      scheme: http
      s3CredentialsSecret:
        secretName: minio-credentials
        accessKey: MINIO_ROOT_USER
        secretKey: MINIO_ROOT_PASSWORD
