apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - vault-secrets.yaml
  - serviceaccount.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - bucket-init-job.yaml
  - dspa.yaml
