apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: fleet-manager
  namespace: fleet-ops
  labels:
    app: fleet-manager
    phase: phase-1
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: workloads/fleet-manager/container/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: fleet-manager:latest
  triggers: []
