apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mlflow-s3-credentials.yaml
  - cnpg-cluster.yaml
  - minio-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - minio-bucket-init-job.yaml
  - mlflow.yaml
