apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mlflow-s3-credentials
  namespace: mlflow
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: kv
  path: mlflow/s3
  destination:
    name: mlflow-s3-credentials
    create: true
    overwrite: true
  refreshAfter: 1h
