apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: git-source-secret
  namespace: omni-streaming
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: kv
  path: argocd/repo-creds
  destination:
    name: git-source-secret
    create: true
    overwrite: true
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      templates:
        username:
          text: git
        password:
          text: '{{ get .Secrets "token" }}'
  refreshAfter: 1h
