apiVersion: v1
kind: Service
metadata:
  name: mission-dispatcher
  namespace: robot-edge
  labels:
    app: mission-dispatcher
spec:
  selector:
    app: mission-dispatcher
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  type: ClusterIP
