---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: isaacsim-streaming-client
  namespace: omni-streaming
  labels:
    app.kubernetes.io/part-of: kit-appstreaming
spec:
  source:
    type: Git
    git:
      uri: https://github.com/jeremyary/industrial-ai-showcase.git
      ref: main
    sourceSecret:
      name: git-source-secret
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: workloads/streaming-client/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: isaacsim-streaming-client:latest
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
  triggers:
    - type: ConfigChange
