apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: companion
rendezvousIP: 10.0.0.80
hosts:
  - hostname: companion-0
    interfaces:
      - name: enp1s0
        macAddress: 52:54:00:0c:01:01
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          mac-address: 52:54:00:0c:01:01
          ipv4:
            enabled: true
            address:
              - ip: 10.0.0.80
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.0.0.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.0.0.1
            next-hop-interface: enp1s0
            table-id: 254
