apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: loki-s3
  namespace: openshift-logging
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: kv
  path: loki/s3
  destination:
    name: loki-s3
    create: true
    overwrite: true
  refreshAfter: 1h
