apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: security
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/jeremyary/industrial-ai-showcase.git
        revision: main
        directories:
          - path: infrastructure/gitops/apps/security/*
  template:
    metadata:
      name: 'security-{{path.basename}}'
      labels:
        phase: phase-0
        layer: security
    spec:
      project: default
      source:
        repoURL: https://github.com/jeremyary/industrial-ai-showcase.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
