apiVersion: v1
kind: Namespace
metadata:
  name: robot-edge
  labels:
    phase: phase-1
    layer: workload
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
