apiVersion: v1
kind: Namespace
metadata:
  name: cosmos
  labels:
    phase: phase-1
    layer: workload
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    istio.io/rev: default
