apiVersion: v1
kind: Service
metadata:
  name: cosmos-reason
  namespace: cosmos
  labels:
    app: cosmos-reason
spec:
  selector:
    app: cosmos-reason
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  type: ClusterIP
