{{- if .Values.dashboard.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: dashboard
    {{- include "central.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: "3600s"
spec:
  {{- if .Values.dashboard.route.host }}
  host: {{ .Values.dashboard.route.host }}
  {{- end }}
  to:
    kind: Service
    name: dashboard
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
