apiVersion: v1
kind: Service
metadata:
  name: central-broker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: central-broker
    {{- include "central.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mqtt
      port: {{ .Values.centralBroker.mqttPort }}
      targetPort: mqtt
    - name: websocket
      port: {{ .Values.centralBroker.websocketPort }}
      targetPort: websocket
  selector:
    app.kubernetes.io/component: central-broker
    {{- include "central.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: dashboard
    {{- include "central.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.dashboard.httpPort }}
      targetPort: http
  selector:
    app.kubernetes.io/component: dashboard
    {{- include "central.selectorLabels" . | nindent 4 }}
{{- if .Values.isaacSim.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: isaac-sim
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: isaac-sim
    {{- include "central.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: camera-http
      port: 8211
      targetPort: camera-http
  selector:
    app.kubernetes.io/component: isaac-sim
    {{- include "central.selectorLabels" . | nindent 4 }}
{{- end }}
