{{- if .Values.isaacSim.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.isaacSim.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "central.labels" . | nindent 4 }}
imagePullSecrets:
  {{- include "central.imagePullSecrets" . | nindent 2 }}
{{- end }}
