apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: camera-adapter
  namespace: fleet-ops
  labels:
    app: camera-adapter
spec:
  podSelector:
    matchLabels:
      app: camera-adapter
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: fleet-ops
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-ingress
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-monitoring
      ports:
        - protocol: TCP
          port: 8083
