apiVersion: v1
kind: Service
metadata:
  name: camera-adapter
  namespace: fleet-ops
  labels:
    app: camera-adapter
spec:
  selector:
    app: camera-adapter
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
  type: ClusterIP
