apiVersion: v1
kind: Service
metadata:
  name: isaac-sim
  namespace: isaac-sim
  labels:
    app: isaac-sim
spec:
  selector:
    app: isaac-sim
  ports:
    - name: webrtc
      port: 49100
      targetPort: webrtc
      protocol: TCP
    - name: livestream
      port: 8011
      targetPort: livestream
      protocol: TCP
    - name: kit-app
      port: 8211
      targetPort: kit-app
      protocol: TCP
  type: ClusterIP
