apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ngc-api-key
  namespace: isaac-sim
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: kv
  path: ngc/api-key
  destination:
    name: ngc-api-key
    create: true
    overwrite: true
  refreshAfter: 1h
