apiVersion: v1
kind: Service
metadata:
  name: fake-camera
  namespace: warehouse-edge
  labels:
    app: fake-camera
spec:
  selector:
    app: fake-camera
  ports:
    - name: http
      port: 8085
      targetPort: http
      protocol: TCP
  type: ClusterIP
