apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nucleus-passwords
  namespace: isaac-sim
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: kv
  path: nucleus/passwords
  destination:
    name: nucleus-passwords
    create: true
    overwrite: true
  refreshAfter: 1h
