apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: companion-only
  namespace: companion
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            role: companion
