apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: companion-git-source-secret
  namespace: open-cluster-management-global-set
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: git-source-secret-warehouse-edge
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: warehouse-edge
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: git-source-secret
                  namespace: warehouse-edge
                type: kubernetes.io/basic-auth
                data:
                  username: '{{hub fromSecret "open-cluster-management-global-set" "git-repo-creds" "username" hub}}'
                  password: '{{hub fromSecret "open-cluster-management-global-set" "git-repo-creds" "password" hub}}'
