apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omniverse-nucleus

resources:
  - serviceaccount.yaml
  - job.yaml

configMapGenerator:
  - name: nucleus-seeder-scripts
    files:
      - seed.py
  - name: nucleus-seeder-scene
    files:
      - Warehouse_edit.usd=../../../../../workloads/isaac-sim/scenes/Warehouse_edit.usd

generatorOptions:
  disableNameSuffixHash: true
