apiVersion: v1
kind: Service
metadata:
  name: mes-stub
  namespace: fleet-ops
  labels:
    app: mes-stub
spec:
  selector:
    app: mes-stub
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
  type: ClusterIP
