---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: showcase-console-backend
  namespace: fleet-ops
  labels:
    app: showcase-console-backend
spec:
  podSelector:
    matchLabels:
      app: showcase-console-backend
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: fleet-ops
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-ingress
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-monitoring
      ports:
        - protocol: TCP
          port: 8090
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: showcase-console-frontend
  namespace: fleet-ops
  labels:
    app: showcase-console-frontend
spec:
  podSelector:
    matchLabels:
      app: showcase-console-frontend
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: fleet-ops
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-ingress
      ports:
        - protocol: TCP
          port: 8080
