---
apiVersion: v1
kind: Service
metadata:
  name: showcase-console-backend
  namespace: fleet-ops
  labels:
    app: showcase-console-backend
spec:
  selector:
    app: showcase-console-backend
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: showcase-console-frontend
  namespace: fleet-ops
  labels:
    app: showcase-console-frontend
spec:
  selector:
    app: showcase-console-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
