---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: showcase-console-backend
  namespace: fleet-ops
  labels:
    app: showcase-console-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: showcase-console-frontend
  namespace: fleet-ops
  labels:
    app: showcase-console-frontend
