apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - imagestreams.yaml
  - buildconfigs.yaml
  - deployments.yaml
  - services.yaml
  - route.yaml
  - networkpolicies.yaml
