apiVersion: v1
kind: Service
metadata:
  name: obstruction-detector
  namespace: fleet-ops
  labels:
    app: obstruction-detector
spec:
  selector:
    app: obstruction-detector
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
  type: ClusterIP
