apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - fake-camera-b-serviceaccount.yaml
  - fake-camera-b-imagestream.yaml
  - fake-camera-b-buildconfig.yaml
  - fake-camera-b-deployment.yaml
  - fake-camera-b-service.yaml
  - mission-dispatcher-b-serviceaccount.yaml
  - mission-dispatcher-b-imagestream.yaml
  - mission-dispatcher-b-buildconfig.yaml
  - mission-dispatcher-b-configmap.yaml
  - mission-dispatcher-b-deployment.yaml
  - mission-dispatcher-b-service.yaml
  - policy-version.yaml
