apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - minio-credentials.yaml
  - minio-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - bucket-init-job.yaml
