apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vault-connection.yaml
  - vault-auth.yaml
  - vault-static-secret.yaml
  - minio-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - bucket-init-job.yaml
