apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: obs-minio-credentials
  namespace: obs-storage
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: kv
  path: obs/s3
  destination:
    name: obs-minio-credentials
    create: true
    overwrite: true
  refreshAfter: 1h
