apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: companion-network-baseline
  namespace: open-cluster-management-global-set
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: networkpolicy-baseline-warehouse-edge
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: deny-all-ingress
                  namespace: warehouse-edge
                spec:
                  podSelector: {}
                  policyTypes:
                    - Ingress
