apiVersion: modelregistry.opendatahub.io/v1beta1
kind: ModelRegistry
metadata:
  name: wbc-model-registry
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  rest:
    port: 8080
  grpc:
    port: 9090
  postgres:
    host: wbc-model-registry-postgres
    port: 5432
    database: wbc_model_registry
    username: mlmduser
    skipDBCreation: false
    sslMode: disable
    passwordSecret:
      name: wbc-model-registry-db
      key: POSTGRES_PASSWORD
