apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-creds
  namespace: openshift-gitops
spec:
  vaultAuthRef: vault
  type: kv-v2
  mount: kv
  path: argocd/repo-creds
  destination:
    name: repo-industrial-ai-showcase
    create: true
    overwrite: true
    labels:
      argocd.argoproj.io/secret-type: repository
    transformation:
      excludeRaw: true
      templates:
        type:
          text: git
        url:
          text: https://github.com/jeremyary/industrial-ai-showcase.git
        password:
          text: '{{ get .Secrets "token" }}'
        username:
          text: git
  refreshAfter: 1h
